apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cpu-load-blinkt-k8s
  labels:
    app: cpu-load-blinkt
    teir: node
spec:
  selector:
    matchLabels:
      name: cpu-load-blinkt
  template:
    metadata:
      labels:
        name: cpu-load-blinkt
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      securityContext:
        runAsUser: 1000
        fsGroup: 997
      containers:
      - name: cpu-load-blinkt
        image: heskew/cpu-load-blinkt-k8s:upd
        imagePullPolicy: Always
        lifecycle:
         preStop:
           exec:
             #Hacky way to shut off the lights, otherwise the container won't get SIGTERM right      
             command: ["kill", "-TERM", "1"]
        volumeMounts:
        - name: devmem
          mountPath: /dev/mem
        securityContext:
          privileged: true
      volumes:
      - name: devmem
        hostPath:
          path: /dev/gpiomem
